### ISSUE TITLE
the input of linear1 

### ISSUE THREAD

**Issue by sbaban** [FraLotito/continuous-bag-of-words#3]
self.linear1 = nn.Linear(embedding_dim, 128)
Hi, why the input is embedding_dim, not 2*context*embedding_dim

**Comment by FraLotito** [comment]
It doesn't really make sense 2contextembedding_dim as input dimension..

**Comment by sbaban** [comment]
@FraLotito 
Oh, I neglected the sum operation you did.
I make a mistake, I concatenate the four embeddings. But they should be summed   in the paper of CBOW model. I test the two means, find that the sum is better than concat.
